service: news
runtime: nodejs18

# Configuración de escalado automático
automatic_scaling:
  # Modifica estos valores según tus necesidades.
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.5
  min_pending_latency: 30ms
  max_pending_latency: automatic

# Handlers define how requests to your app should be handled.
handlers:
  # Define a wildcard handler for all URLs.
  - url: /.*
    script: node src/server.js



# Configuración de variables de entorno
env_variables:
  # Agrega aquí las variables de entorno que necesite tu aplicación
  # En este ejemplo, se establece el puerto del servidor en 8080
  PORT: 8080
  DB_HOST : 34.148.245.1
  DB_USER : root
  DB_PASS :  vP--<aO32dfdNn*P
  DB_DATABASE : news