# Build stage
FROM node:14-alpine3.14 AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci --no-optional && \
    npm cache clean --force
COPY . .
RUN npm run build

# Production stage
FROM node:14-alpine3.14
WORKDIR /app
COPY . /app/.
RUN npm ci --production --no-optional && \
    npm cache clean --force
COPY --from=build /app/dist ./dist
ENV PORT=8100
EXPOSE 8100
CMD [ "npm", "start" ]