openapi: 3.0.3
info:
  title: CryptoBot - News
  description: >-
    microservicio encargado del manejo del seguimiento de noticias relacionadas a las cryptomonedas de interes del usuario cliente
  version: 0.1.0
paths:
  /news/follow:
    post:
      tags:
        - news
      summary: insert or delets the follow of  the user into a crypto 
      description: saves the information of the crypto that the user follows or delets that follow if already exits to cancel it
      requestBody:
        description: creates follow
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/follow'
        required: true
      responses:
        '200':
          description: follow inserted OR follow deleted

        '500':
          description: Internal error inserting OR deleting follow
          
  /news/notificacion/:user_id:
    get:
      tags:
        - news
      summary: search a notice related to the user´s cryptos of interest
      description: search for a notice using a crypto that the user follow

        
      responses:
        '200':
          description: notice

        '500':
          description: Internal error  finding notice
                
  /news/consult:
    get:
      tags:
        - news
      summary: respond with the crypto page for notices
      description: respond with the crypto page for notices

        
      responses:
        '200':
          description: link send

        '500':
          description: Internal error getting link
  
components:
  schemas:
    
    follow:
      type: object
      properties:
        user_id:
          type: integer
          example: '123'
        crypto_name:
          type: string
          example: bitcoin

    
